library(rvest)
library(robotstxt)
library(dplyr)
path<-paths_allowed("https://www.mygov.in/corona-data/covid19-statewise-status/")
link<-"https://www.mygov.in/corona-data/covid19-statewise-status/"
web<-read_html(link)
states <- web%>%html_nodes(".field-type-list-text .even")%>%html_text()
View(states)
Confirmed<-web%>%html_nodes(".field-name-field-total-confirmed-indians .even")%>%html_text()
View(Confirmed)
Cured<-web%>%html_nodes(".field-name-field-cured .even")%>%html_text()
Death<-web%>%html_nodes(".field-name-field-deaths .even")%>%html_text()
CovidIndia<-data.frame(States,Cured,Death)
View(CovidIndia)
str(CovidIndia)
CovidIndia$confirmed<- as.numeric(CovidIndia$Confirmed)
CovidIndia$confirmed<- as.numeric(CovidIndia$Cured)
CovidIndia$confirmed<- as.numeric(CovidIndia$Death)
str(CovidIndia)